### ISSUE TITLE
how to check the imu converted to odom right?

### ISSUE THREAD

**Issue by himhan34** [nadiawangberg/imu_to_odom#2]
hello. i am quite newbie to ros. 
so i installed the package rightly

if you don't mind can you tell me what to do next?

i have my imu data.
the topic is  imu/data

how can i conect these things!

**Comment by shijjplayerya** [comment]
> hello. i am quite newbie to ros. 
> so i installed the package rightly
> 
> if you don't mind can you tell me what to do next?
> 
> i have my imu data.
> the topic is  imu/data
> 
> how can i conect these things!

hi sir,i think i have an answer.
find that on the fourteenth row, in `src/imu_to_odom.c`
```c++
      nh_.subscribe("/uav/sensors/imu", kROSQueueLength, &OdomPredictor::imuCallback, this);
```

change `/uav/sensors/imu` to `/imu/data`
